version: "3"
name: "transaction-app"
services:

  backend:
    container_name: app-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app

  db:
    image: postgres:14
    container_name: transaction-scheduler-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: transactions-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root